
// Mirror Enums from contract (can be auto-generated by Anchor types)
export enum PaymentMode {
    Direct,
    Advance,
}

export enum OrderStatus {
    Unpaid,
    Paid,
    Shipped,
    Confirmed,
    Completed,
    Unfulfilled,
}

// Simplified Product Type for DB simulation
export interface Product {
    id: string;
    name: string;
    priceLamports: string; // Store as string Lamports (USDC smallest unit)
    seller: string; // Seller's PublicKey as string
    imageUrl?: string;
}

// Type for Order data fetched from chain (adjust based on Anchor generated types if available)
export interface OrderData {
    publicKey: string; // Address of the OrderState PDA
    buyer: string;
    seller: string;
    mint: string;
    tradeId: string;
    orderAmount: string;
    paidAmount: string;
    claimedAmount: string;
    paymentMode: PaymentMode;
    advancePercentage: number;
    status: OrderStatus;
    createdAt: string;
    paidAt: string;
    shippedAt: string;
    confirmedAt: string;
    completedAt: string;
}
